### ISSUE TITLE
Cannot resolve method getId in line 66 in GitHubUserPresenter class

### ISSUE THREAD

**Issue by zkvarz** [viraj49/Realm_android-injection-rx-test#1]
There is a problem when I cloned your project to see the details.
Firstly, I’ve got “Cannot resolve method getId” error in the line 66 in GitHubUserPresenter class.
The most weird thing for me was… that project compiled and ran. I saw it opened and then not responding message appeared.
P.S. I didn’t change anything when I ran your project.

**Comment by viraj-tank-sociomantic** [comment]
@zkvarz Hello, I am back from vacation and I just followed the steps, but it seems to be working fine, could you please add more details, from the line number I figured you are using safe-integration project.

**Comment by viraj49** [comment]
@zkvarz Hello, I am back from vacation and just followed the steps you reported, but the project seems to be working fine, could you please add more details. From the line number I figured you are using safe-integration project.

**Comment by zkvarz** [comment]
@viraj49 No, it both on deep and safe-integration it shows the same warnings.
I have such configuration: Windows 10, Android Studio 2.2, emulator Nexus 10 API 23.
The same also happens in GitHubUserProfileFragment in the line 141 "gitHubUserProfile.getName()" cannot resolve method getName() and in other lines too.
I tried again, even there where warnings app ran. But in pull to refresh app freezes and then it shows SnackBar with "Error loading data" message.

**Comment by mdzht** [comment]
zkvarz it's not error.  it's lombok warning. cause @Setter
@Getter annotations using

**Comment by viraj49** [comment]
Thanks @mdzht, closing this issue.
